apiVersion: apps/v1
kind: Deployment
metadata:
  name: casper-3
spec:
  template:
    spec:
      containers:
        - name: casper-3
          image: gathertown/casper-3:6392065
          envFrom:
            - secretRef:
                name: token
          env:
            - name: ENV
              value: development
            - name: PROVIDER
              value: cloudflare
            - name: SUBDOMAIN
              value: ""
            - name: ZONE
              value: gather.town
            - name: INTERVAL
              value: "60"
            - name: LABEL_KEY
              value: doks.digitalocean.com/node-pool
            - name: LABEL_VALUE
              value: sfu
