version: 2.1

orbs:
  docker: circleci/docker@1.4.0
  k8s: digitalocean/k8s@0.1.1
  kubernetes: circleci/kubernetes@0.11.2
  slack: circleci/slack@4.1.4
  browser-tools: circleci/browser-tools@1.1.1
  jq: circleci/jq@2.2.0
  kuz: finc/kustomize@0.0.1

executors:
  build-executor:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium

commands:
  deploy:
    description: "deliver application to kubernetes cluster"
    parameters:
      token:
        type: string
        default: "TF_VAR_do_token"
      environment:
        type: string
      image:
        type: string
        default: "gathertown/casper-3"
      cluster:
        type: string
        default: abcd
      provider:
        type: string
      subdomain:
        type: string
        default: ""
      zone:
        type: string
    steps:
      - checkout
      - get-commit-shorthash
      - k8s/install
      - kuz/install:
          version: "v4.0.1"
      - k8s/initialize:
          cluster: << parameters.cluster >>
      - run:
          environment:
            - ENV: <<parameters.environment>>
            - PROVIDER: <<parameters.provider>>
            - SUBDOMAIN: <<parameters.subdomain>>
            - ZONE: <<parameters.zone>>
          command: |
            mkdir ~/.secrethub
            echo ${SECRETHUB_CREDENTIAL} > ~/.secrethub/credential
            curl -LO https://github.com/secrethub/secrethub-cli/releases/download/v0.41.2/secrethub-v0.41.2-linux-amd64.tar.gz
            tar zxvf secrethub-v0.41.2-linux-amd64.tar.gz -C /tmp
            mkdir -p deployments/base/secrets deployments/overlays/cluster/secrets
            /tmp/bin/secrethub read -n gather/gather-town/deploy/terraform/dockerhub_credentials > deployments/base/secrets/priv-docker-registry
            /tmp/bin/secrethub read -n gather/gather-town/deploy/terraform/<<parameters.token>>  > deployments/overlays/cluster/secrets/TOKEN
            cd deployments/overlays/cluster
            kustomize edit set image << parameters.image >>:${SHORTHASH}
            envsubst < deployment.yaml > deployment-temp.yaml
            rm -f deployment.yaml
            mv deployment-temp.yaml deployment.yaml
            kustomize build . | kubectl apply -f -
  get-commit-shorthash:
    steps:
      - run:
          name: Get git commit shorthash
          command: |
            echo 'export SHORTHASH="$(git rev-parse --short HEAD)"' >> $BASH_ENV
  build-and-push:
    description: "build and push docker image to registry"
    parameters:
      image:
        type: string
        default: "gathertown/casper-3"
      dockerfile:
        type: string
        default: "Dockerfile"
    steps:
      - checkout
      - get-commit-shorthash
      - docker/build:
          dockerfile: <<parameters.dockerfile>>
          image: <<parameters.image>>
          tag: $SHORTHASH
      - docker/check
      - docker/push:
          image: <<parameters.image>>
          tag: $SHORTHASH

jobs:
  build-and-push:
    parameters:
      executor:
        default: build-executor
        type: executor
      image:
        type: string
        default: "gathertown/casper-3"
      dockerfile:
        type: string
        default: "Dockerfile"
    executor: <<parameters.executor>>
    steps:
      - build-and-push:
          dockerfile: <<parameters.dockerfile>>
          image: <<parameters.image>>
  deploy:
    parameters:
      executor:
        default: build-executor
        type: executor
      environment:
        type: string
      token:
        type: string
      cluster:
        type: string
      provider:
        type: string
      subdomain:
        type: string
        default: ""
      zone:
        type: string
    executor: <<parameters.executor>>
    steps:
      - deploy:
          environment: <<parameters.environment>>
          token: <<parameters.token>>
          cluster: <<parameters.cluster>>
          provider: <<parameters.provider>>
          subdomain: <<parameters.subdomain>>
          zone: <<parameters.zone>>

workflows:
  build-and-push:
    jobs:
      - build-and-push:
          dockerfile: Dockerfile
          filters:
            branches:
              only:
                - develop
                - staging
                - main

      # development cluster
      - deploy:
          name: development
          requires:
            - build-and-push
          environment: development
          token: TF_VAR_do_token
          cluster: $K8S_DEV_NYC1
          provider: digitalocean
          subdomain: dev
          zone: k8s.gather.town
          filters:
            branches:
              only:
                - develop

      # staging clusters
      - deploy:
          name: staging-do-nyc3-a
          requires:
            - build-and-push
          token: TF_VAR_cf_token
          environment: staging-do-nyc3-a
          cluster: $K8S_STG_NYC3_A
          provider: cloudflare
          subdomain: nyc3-a.stg.do
          zone: gather.town
          filters:
            branches:
              only:
                - staging
      - deploy:
          name: staging-do-fra1-a
          requires:
            - build-and-push
          token: TF_VAR_cf_token
          environment: staging-do-fra1-a
          cluster: $K8S_STG_FRA1_A
          provider: cloudflare
          subdomain: fra1-a.stg.do
          zone: gather.town
          filters:
            branches:
              only:
                - staging

      # production clusters
      - deploy:
          name: production-do-blr1-a
          requires:
            - build-and-push
          token: TF_VAR_cf_token
          environment: production-do-blr1-a
          cluster: $K8S_PROD_BLR1_A
          provider: cloudflare
          subdomain: blr1-a.prod.do
          zone: gather.town
          filters:
            branches:
              only:
                - main
      - deploy:
          name: production-do-fra1-a
          requires:
            - build-and-push
          token: TF_VAR_cf_token
          environment: production-do-fra1-a
          cluster: $K8S_PROD_FRA1_A
          provider: cloudflare
          subdomain: fra1-a.prod.do
          zone: gather.town
          filters:
            branches:
              only:
                - main
      - deploy:
          name: production-do-sgp1-a
          requires:
            - build-and-push
          token: TF_VAR_cf_token
          environment: production-do-sgp1-a
          cluster: $K8S_PROD_SGP1_A
          provider: cloudflare
          subdomain: sgp1-a.prod.do
          zone: gather.town
          filters:
            branches:
              only:
                - main
      - deploy:
          name: production-do-sfo3-a
          requires:
            - build-and-push
          token: TF_VAR_cf_token
          environment: production-do-sfo3-a
          cluster: $K8S_PROD_SFO3_A
          provider: cloudflare
          subdomain: sfo3-a.prod.do
          zone: gather.town
          filters:
            branches:
              only:
                - main
      - deploy:
          name: production-do-nyc3-a
          requires:
            - build-and-push
          token: TF_VAR_cf_token
          environment: production-do-nyc3-a
          cluster: $K8S_PROD_NYC3_A
          provider: cloudflare
          subdomain: nyc3-a.prod.do
          zone: gather.town
          filters:
            branches:
              only:
                - main

      # legacy clusters
      - deploy:
          name: staging
          requires:
            - build-and-push
          token: TF_VAR_do_token
          environment: staging
          cluster: $K8S_STG_LEGACY
          provider: digitalocean
          subdomain: stg
          zone: k8s.gather.town
          filters:
            branches:
              only:
                - staging
      - deploy:
          name: production
          requires:
            - build-and-push
          environment: production
          token: TF_VAR_cf_token
          cluster: $K8S_PROD_LEGACY
          provider: cloudflare
          subdomain: ""
          zone: gather.town
          filters:
            branches:
              only:
                - main
