# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- namespace.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml

secretGenerator:
  - name: priv-docker-registry
    files:
      - .dockerconfigjson=secrets/priv-docker-registry
    type: kubernetes.io/dockerconfigjson
