apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: casper-3
    scope: cluster
  name: casper-3
  namespace: infrastructure
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
    - infrastructure
  selector:
    matchLabels:
      app: casper-3
