apiVersion: apps/v1
kind: Deployment
metadata:
  name: casper-3
spec:
  template:
    spec:
      containers:
        - name: casper-3
          image: gathertown/casper-3:6392065
          envFrom:
            - secretRef:
                name: casper-3-environment
          env:
            - name: ENV
              value: ${ENV}
            - name: LOGLEVEL
              value: ${LOGLEVEL}
            - name: PROVIDER
              value: ${PROVIDER}
            - name: SUBDOMAIN
              value: ${SUBDOMAIN}
            - name: ZONE
              value: ${ZONE}
            - name: CLOUDFLARE_PROXIED_NODE_POOLS
              value: "${CLOUDFLARE_PROXIED_NODE_POOLS}"
            - name: LABEL_VALUES
              value: "${LABEL_VALUES}"
