apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  ownedBY: infra

images:
- name: gathertown/casper-3
  newTag: 3bdb171

patchesStrategicMerge:
- deployment.yaml

resources:
- ../../base/
- prometheusrules.yaml
