apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

commonLabels:
  ownedBY: infra

images:
- name: gathertown/casper-3
  newTag: bebf8f6

patchesStrategicMerge:
- deployment.yaml


secretGenerator:
- files:
  - secrets/TOKEN
  name: token
resources:
- ../../base/
